import '@/public/styles/globals.css'
import { geistSans, geistMono } from '@/public/fonts/appFonts'
import type { Metadata } from 'next'
import { Nav, NavLink } from '@/components/nav/nav'
import { Footer } from '../components/nav/footer'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={`min-h-screen flex flex-col ${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Nav>
          <NavLink href="/introduction">Introduction</NavLink>
          <NavLink href="/service">Service</NavLink>
          <NavLink href="/calendar">Calendar</NavLink>
        </Nav>
        <main className="relative isolate overflow-hidden bg-white py-24 sm:py-32 px-6 lg:px-8 max-w-2xl lg:max-w-6xl mx-auto p">
          {children}
        </main>
        <Footer />
      </body>
    </html>
  )
}
